import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import PptxGenJS from 'pptxgenjs';

export const dynamic = 'force-dynamic';

const SlideSchema = z.object({
  index: z.number().int().positive(),
  heading: z.string().min(1),
  bullets: z.array(z.string()).default([]),
  imageHints: z.array(z.string()).optional(),
});

const RequestSchema = z.object({
  title: z.string().min(1).max(180),
  slides: z.array(SlideSchema).min(1).max(100),
});

const sanitizeFilename = (value: string): string =>
  value
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60) || 'presentation';

export async function POST(req: NextRequest) {
  try {
    const parsed = RequestSchema.safeParse(await req.json());
    if (!parsed.success) return NextResponse.json({ error: 'Invalid payload' }, { status: 400 });

    const { title, slides } = parsed.data;
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = 'Cautie';
    pptx.company = 'Cautie';
    pptx.subject = title;
    pptx.title = title;

    for (const slideItem of slides) {
      const slide = pptx.addSlide();
      slide.background = { color: 'F4F3EE' };
      slide.addText(title, {
        x: 0.5,
        y: 0.25,
        w: 12.3,
        h: 0.4,
        fontFace: 'Calibri',
        fontSize: 12,
        color: '6B6B66',
      });
      slide.addText(`${slideItem.index}. ${slideItem.heading}`, {
        x: 0.7,
        y: 0.85,
        w: 11.8,
        h: 0.9,
        fontFace: 'Calibri',
        bold: true,
        fontSize: 29,
        color: '111111',
        breakLine: true,
      });

      const bulletLines = slideItem.bullets.slice(0, 6).map((line) => ({ text: line || ' ' }));
      if (bulletLines.length > 0) {
        slide.addText(bulletLines, {
          x: 1.0,
          y: 2.05,
          w: 11.0,
          h: 4.2,
          fontFace: 'Calibri',
          fontSize: 19,
          color: '222222',
          bullet: { indent: 16 },
          breakLine: true,
          margin: 2,
        });
      }

      slide.addText(`Generated by Cautie • ${new Date().toLocaleDateString('en-US')}`, {
        x: 0.7,
        y: 6.8,
        w: 11.8,
        h: 0.3,
        fontFace: 'Calibri',
        fontSize: 10,
        color: '7A7A74',
        align: 'right',
      });
    }

    const base64 = (await pptx.write({ outputType: 'base64' })) as string;
    const buffer = Buffer.from(base64, 'base64');
    const filename = `${sanitizeFilename(title)}.pptx`;

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Failed to generate presentation file' }, { status: 500 });
  }
}

