import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import PptxGenJS from 'pptxgenjs';

export const dynamic = 'force-dynamic';

const SlideSchema = z.object({
  index: z.number().int().positive(),
  heading: z.string().min(1),
  bullets: z.array(z.string()).default([]),
  imageHints: z.array(z.string()).optional(),
});

const RequestSchema = z.object({
  title: z.string().min(1).max(2000),
  slides: z.array(SlideSchema).min(1).max(120),
});

const sanitizeFilename = (value: string): string =>
  value
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60) || 'presentation';

const cleanTitle = (value: string): string => value.replace(/\s+/g, ' ').trim().slice(0, 160) || 'Presentation';

const cleanBullet = (value: string): string => value.replace(/\s+/g, ' ').trim().slice(0, 180);

export async function POST(req: NextRequest) {
  try {
    const parsed = RequestSchema.safeParse(await req.json());
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid payload', details: parsed.error.issues }, { status: 400 });
    }

    const title = cleanTitle(parsed.data.title);
    const slides = parsed.data.slides;

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = 'Cautie';
    pptx.company = 'Cautie';
    pptx.subject = title;
    pptx.title = title;

    for (const slideItem of slides) {
      const slide = pptx.addSlide();
      slide.background = { color: 'F4F3EE' };

      slide.addText(title, {
        x: 0.6,
        y: 0.28,
        w: 11.8,
        h: 0.35,
        fontFace: 'Calibri',
        fontSize: 11,
        color: '6B6B66',
      });

      slide.addText(`${slideItem.index}. ${cleanTitle(slideItem.heading).slice(0, 100)}`, {
        x: 0.7,
        y: 0.82,
        w: 11.6,
        h: 0.92,
        fontFace: 'Calibri',
        bold: true,
        fontSize: 30,
        color: '111111',
        breakLine: true,
      });

      const bullets = slideItem.bullets
        .map((line) => cleanBullet(line))
        .filter(Boolean)
        .slice(0, 8)
        .map((line) => ({ text: line }));

      if (bullets.length > 0) {
        slide.addText(bullets, {
          x: 1.02,
          y: 2.0,
          w: 10.8,
          h: 4.4,
          fontFace: 'Calibri',
          fontSize: 20,
          color: '222222',
          bullet: { indent: 18 },
          breakLine: true,
          margin: 2,
        });
      }

      slide.addText(`Generated by Cautie | ${new Date().toLocaleDateString('en-US')}`, {
        x: 0.7,
        y: 6.86,
        w: 11.6,
        h: 0.28,
        fontFace: 'Calibri',
        fontSize: 10,
        color: '7A7A74',
        align: 'right',
      });
    }

    const base64 = (await pptx.write({ outputType: 'base64' })) as string;
    const buffer = Buffer.from(base64, 'base64');
    const filename = `${sanitizeFilename(title)}.pptx`;

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch {
    return NextResponse.json({ error: 'Failed to generate presentation file' }, { status: 500 });
  }
}
