import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import PptxGenJS from 'pptxgenjs';
import { createClient } from '@/lib/supabase/server';
import { getValidMicrosoftAccessToken } from '@/lib/integrations/microsoft-store';
import { checkRateLimit } from '@/lib/security/request-guards';

export const dynamic = 'force-dynamic';

const SlideSchema = z.object({
  index: z.number().int().positive(),
  heading: z.string().min(1),
  bullets: z.array(z.string()).default([]),
  speakerNotes: z.string().optional(),
});

const RequestSchema = z.object({
  title: z.string().min(1).max(2000),
  slides: z.array(SlideSchema).min(1).max(120),
  includeSpeakerNotes: z.boolean().optional(),
  destination: z
    .object({
      kind: z.enum(['download', 'microsoft', 'google']),
      targetApp: z.enum(['powerpoint', 'sharepoint', 'google-slides']).optional(),
    })
    .optional(),
});

const sanitizeFilename = (value: string): string =>
  value
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60) || 'presentation';

const cleanTitle = (value: string): string => value.replace(/\s+/g, ' ').trim().slice(0, 160) || 'Presentation';

const cleanBullet = (value: string): string => value.replace(/\s+/g, ' ').trim().slice(0, 180);

async function renderPptxBuffer(input: {
  title: string;
  slides: Array<{ index: number; heading: string; bullets: string[]; speakerNotes?: string }>;
  includeSpeakerNotes: boolean;
}) {
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'Cautie';
  pptx.company = 'Cautie';
  pptx.subject = input.title;
  pptx.title = input.title;

  for (const slideItem of input.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: 'F4F3EE' };

    slide.addText(input.title, {
      x: 0.6,
      y: 0.28,
      w: 11.8,
      h: 0.35,
      fontFace: 'Calibri',
      fontSize: 11,
      color: '6B6B66',
    });

    slide.addText(`${slideItem.index}. ${cleanTitle(slideItem.heading).slice(0, 100)}`, {
      x: 0.7,
      y: 0.82,
      w: 11.6,
      h: 0.92,
      fontFace: 'Calibri',
      bold: true,
      fontSize: 30,
      color: '111111',
      breakLine: true,
    });

    const bullets = slideItem.bullets
      .map((line) => cleanBullet(line))
      .filter(Boolean)
      .slice(0, 8)
      .map((line) => ({ text: line }));

    if (bullets.length > 0) {
      slide.addText(bullets, {
        x: 1.02,
        y: 2.0,
        w: 10.8,
        h: 4.4,
        fontFace: 'Calibri',
        fontSize: 20,
        color: '222222',
        bullet: { indent: 18 },
        breakLine: true,
        margin: 2,
      });
    }

    if (input.includeSpeakerNotes && slideItem.speakerNotes?.trim()) {
      slide.addNotes(slideItem.speakerNotes.trim().slice(0, 1200));
    }

    slide.addText(`Generated by Cautie | ${new Date().toLocaleDateString('en-US')}`, {
      x: 0.7,
      y: 6.86,
      w: 11.6,
      h: 0.28,
      fontFace: 'Calibri',
      fontSize: 10,
      color: '7A7A74',
      align: 'right',
    });
  }

  const base64 = (await pptx.write({ outputType: 'base64' })) as string;
  return Buffer.from(base64, 'base64');
}

async function uploadToMicrosoftDrive(input: {
  accessToken: string;
  filename: string;
  data: Buffer;
}) {
  const path = encodeURIComponent(`Cautie Exports/${input.filename}`).replace(/%2F/g, '/');
  const response = await fetch(`https://graph.microsoft.com/v1.0/me/drive/root:/${path}:/content`, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${input.accessToken}`,
      'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    },
    body: new Uint8Array(input.data),
    cache: 'no-store',
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = payload?.error?.message || 'Microsoft cloud export failed';
    throw new Error(message);
  }
  return {
    id: typeof payload?.id === 'string' ? payload.id : '',
    webUrl: typeof payload?.webUrl === 'string' ? payload.webUrl : '',
    name: typeof payload?.name === 'string' ? payload.name : input.filename,
  };
}

export async function POST(req: NextRequest) {
  const rateLimit = checkRateLimit(req, { key: 'presentation-export', limit: 25, windowMs: 60_000 });
  if (!rateLimit.ok) return rateLimit.response;

  try {
    const parsed = RequestSchema.safeParse(await req.json());
    if (!parsed.success) {
      return NextResponse.json({ error: 'Invalid payload', details: parsed.error.issues }, { status: 400 });
    }

    const title = cleanTitle(parsed.data.title);
    const slides = parsed.data.slides;
    const includeSpeakerNotes = Boolean(parsed.data.includeSpeakerNotes);
    const destination = parsed.data.destination?.kind || 'download';
    const filename = `${sanitizeFilename(title)}.pptx`;

    const buffer = await renderPptxBuffer({
      title,
      slides,
      includeSpeakerNotes,
    });

    if (destination === 'download') {
      return new NextResponse(buffer, {
        status: 200,
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
          'Content-Disposition': `attachment; filename="${filename}"`,
          'Cache-Control': 'no-store',
        },
      });
    }

    if (destination === 'google') {
      return NextResponse.json(
        {
          error: 'Google cloud export is not configured in this workspace yet. Use Microsoft export or download.',
          fallback: 'download',
        },
        { status: 501 }
      );
    }

    const cookieStore = cookies();
    const supabase = await createClient(cookieStore);
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const tokenState = await getValidMicrosoftAccessToken(supabase, user.id);
    if (!tokenState?.accessToken) {
      return NextResponse.json(
        {
          error: 'Microsoft account not connected',
          code: 'microsoft_not_connected',
          fallback: 'download',
        },
        { status: 409 }
      );
    }

    const uploaded = await uploadToMicrosoftDrive({
      accessToken: tokenState.accessToken,
      filename,
      data: buffer,
    });

    return NextResponse.json({
      ok: true,
      destination: 'microsoft',
      targetApp: parsed.data.destination?.targetApp || 'powerpoint',
      fileName: filename,
      fileId: uploaded.id,
      webUrl: uploaded.webUrl,
      openLabel:
        parsed.data.destination?.targetApp === 'sharepoint'
          ? 'Open in SharePoint'
          : 'Open in PowerPoint',
      fallback: 'download',
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        error: String(error?.message || 'Failed to generate presentation file'),
        fallback: 'download',
      },
      { status: 500 }
    );
  }
}
